In [1]:
from selenium import webdriver
import pandas as pd
from bs4 import BeautifulSoup
import urllib.request as req
import pandas as pd
import requests
from io import StringIO
import requests
import time
from selenium.webdriver import Chrome
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser
import os
from naver_crawler import *
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time
import re
import parser
import datetime
from urllib.request import urlopen
import webbrowser
import xmltodict
import json
from ast import literal_eval

<ipython-input-1-e9ca380508bf>:23: DeprecationWarning: The parser module is deprecated and will be removed in future versions of Python
  import parser

In [2]:
# os.chdir('C:\\Users\\shic\\Desktop\\Crawling\\Desktop\\Project')
os.chdir('C:\\Users\\kuri9\\Desktop\\Crawling\\Desktop\\Project')
delay=3
browser = Chrome()
browser.implicitly_wait(delay)

In [12]:
url = 'https://www.kisrating.co.kr/ratingsStatistics/statics_spread.do'
res = requests.get(url)
page_soup = BeautifulSoup(res.text,'lxml')
table = page_soup.select_one('div.table_ty1')
# html -> 문자열
table_html = str(table)
# pandas의 read_html로 테이블 정보 읽기
table_df = pd.read_html(table_html)[0]
table_df.set_index('구분',inplace=True)
table_df

        3월    6월    9월    1년  1년6월    2년    3년    5년
구분
국고채   0.52  0.65  0.82  0.95  1.16  1.31  1.46  1.70
AAA   0.87  0.97  1.12  1.21  1.37  1.57  1.73  1.99
AA+   0.93  1.00  1.16  1.24  1.41  1.61  1.78  2.04
AA    0.97  1.04  1.20  1.28  1.44  1.64  1.82  2.10
AA-   0.99  1.06  1.22  1.31  1.47  1.67  1.85  2.21
A+    1.19  1.26  1.42  1.48  1.63  1.79  2.01  2.61
A     1.33  1.40  1.59  1.66  1.81  2.00  2.32  3.06
A-    1.55  1.65  1.85  1.93  2.11  2.36  2.78  3.67
BBB+  2.19  2.62  3.13  3.39  3.90  4.59  5.33  5.74
BBB   2.57  3.12  3.71  4.06  4.71  5.53  6.38  6.79
BBB-  3.24  3.91  4.64  5.05  5.82  6.68  7.75  8.21

## 한국신용공시

In [188]:
# 창 띄우기
# 신금투 폴더 : os.chdir('C:\\Users\\shic\\Desktop\\Crawling\\Desktop\\Project')
os.chdir('C:\\Users\\kuri9\\Desktop\\Crawling\\Desktop\\Project')
delay=3
browser = Chrome()
browser.implicitly_wait(delay)
url = 'https://www.kisrating.co.kr/ratings/hot_disclosure.do'
browser.get(url)
browser.maximize_window()

In [189]:
# 2010 ~ 2021 date_list 만들기
import time
from datetime import date,timedelta
today= date.today()
date_lst=[]
for i in range(142):
    date_lst.append((today - timedelta(days=30*i)).strftime("%Y.%m.%d"))
len(date_lst),date_lst[-1]

(142, '2009.12.20')

In [190]:
table_DF1 = pd.DataFrame()
table_DF2 = pd.DataFrame()
table_DF3 = pd.DataFrame()
table_DF4 = pd.DataFrame()
table_DF5 = pd.DataFrame()
table_DF6 = pd.DataFrame()
table_DF7 = pd.DataFrame()
table_DF8 = pd.DataFrame()

In [191]:
for i in range(len(date_lst)-1):
    start_date = browser.find_element_by_xpath('//*[@id="startDt"]')
    start_date.clear()
    start_date.send_keys(date_lst[i+1])
    end_date = browser.find_element_by_xpath('//*[@id="endDt"]')
    end_date.clear()
    end_date.send_keys(date_lst[i])
    src_btn = browser.find_element_by_xpath('//*[@id="btnSearch"]')
    src_btn.click()
    browser.implicitly_wait(10)
    
    # 수동으로 2010년 ~ 데이터 선택
    result = browser.page_source
    soup = BeautifulSoup(result, 'html.parser')
    
    table = soup.select('div.table_ty1')
    table_html = str(table)
    
    # 1. 회사채
    table_df1 = pd.read_html(table_html)[0]
    new_index=[]
    for i in range(len(table_df1.columns)):
        new_index.append(table_df1.columns[i][0])
    table_df1.columns = new_index
    table_df1.drop(['Unnamed: 0_level_0','Unnamed: 8_level_0'],axis=1,inplace=True)
    table_df1['Type']='회사채'
    table_DF1=pd.concat([table_DF1,table_df1],axis=0)
    print("table_DF1:",table_DF1.shape)
    
    # 2. 기업어음
    table_df2 = pd.read_html(table_html)[1]
    table_df2.drop('Unnamed: 0',axis=1,inplace=True)
    table_df2['Type']='기업어음'
    table_DF2=pd.concat([table_DF2,table_df2],axis=0)
    print("table_DF2:",table_DF2.shape)
    
    # 3. 전자단기사채
    table_df3 = pd.read_html(table_html)[2]
    table_df3.drop('Unnamed: 0',axis=1,inplace=True)
    table_df3['Type']='전자단기사채'
    table_DF3=pd.concat([table_DF3,table_df3],axis=0)
    print("table_DF3:",table_DF3.shape)
    
    # 4. Issuer Rating
    table_df4 = pd.read_html(table_html)[3]
    new_index=[]
    for i in range(len(table_df4.columns)):
        new_index.append(table_df4.columns[i][1])
    table_df4.columns = new_index
    table_df4.drop(['Unnamed: 0_level_1','Unnamed: 6_level_1'],axis=1,inplace=True)
    table_df4.columns=['회사명', '재무기준일', '평가종류', '직전등급', '직전Outlook', '현재등급', '현재Outlook', '기준통화', '평가일','리포트']
    table_df4['Type']='Issuer Rating'
    table_DF4=pd.concat([table_DF4,table_df4],axis=0)
    print("table_DF4:",table_DF4.shape)
    
    # 5. 보험금지급능력평가
    table_df5 = pd.read_html(table_html)[4]
    new_index=[]
    for i in range(len(table_df5.columns)):
        new_index.append(table_df5.columns[i][1])
    table_df5.columns = new_index
    table_df5.drop(['Unnamed: 0_level_1','Unnamed: 6_level_1'],axis=1,inplace=True)
    table_df5.columns=['회사명', '재무기준일', '평가종류', '직전등급', '직전Outlook', '현재등급', '현재Outlook', '기준통화', '평가일','리포트']
    table_df5['Type']='보험금지급능력평가'
    table_DF5=pd.concat([table_DF5,table_df5],axis=0)
    print("table_DF5:",table_DF5.shape)
    
    # 6. 자산유동화증권
    table_df6 = pd.read_html(table_html)[5]
    table_df6.drop('Unnamed: 0',axis=1,inplace=True)
    table_df6['Type']='자산유동화증권'
    table_DF6=pd.concat([table_DF6,table_df6],axis=0)
    print("table_DF6:",table_DF6.shape)
    
    # 7. 유동화익스포져
    table_df7 = pd.read_html(table_html)[6]
    table_df7.drop('Unnamed: 0',axis=1,inplace=True)
    table_df7['Type']='유동화익스포져'
    table_DF7=pd.concat([table_DF7,table_df7],axis=0)
    print("table_DF7:",table_DF7.shape)

    # 8. Covered Bond
    table_df8 = pd.read_html(table_html)[7]
    table_df8.drop('Unnamed: 0',axis=1,inplace=True)
    table_df8['Type']='Covered Bond'
    table_DF8=pd.concat([table_DF8,table_df8],axis=0)
    print("table_DF8:",table_DF8.shape)

table_DF1: (466, 11)
table_DF2: (131, 9)
table_DF3: (54, 10)
table_DF4: (34, 11)
table_DF5: (5, 11)
table_DF6: (353, 11)
table_DF7: (11, 12)
table_DF8: (0, 12)
table_DF1: (1048, 11)
table_DF2: (231, 9)
table_DF3: (92, 10)
table_DF4: (59, 11)
table_DF5: (6, 11)
table_DF6: (700, 11)
table_DF7: (28, 12)
table_DF8: (0, 12)
table_DF1: (1408, 11)
table_DF2: (271, 9)
table_DF3: (102, 10)
table_DF4: (76, 11)
table_DF5: (13, 11)
table_DF6: (1065, 11)
table_DF7: (51, 12)
table_DF8: (2, 12)
table_DF1: (1858, 11)
table_DF2: (297, 9)
table_DF3: (111, 10)
table_DF4: (89, 11)
table_DF5: (15, 11)
table_DF6: (1287, 11)
table_DF7: (61, 12)
table_DF8: (2, 12)
table_DF1: (2032, 11)
table_DF2: (303, 9)
table_DF3: (114, 10)
table_DF4: (92, 11)
table_DF5: (15, 11)
table_DF6: (1562, 11)
table_DF7: (73, 12)
table_DF8: (3, 12)
table_DF1: (2236, 11)
table_DF2: (303, 9)
table_DF3: (114, 10)
table_DF4: (96, 11)
table_DF5: (17, 11)
table_DF6: (1805, 11)
table_DF7: (86, 12)
table_DF8: (3, 12)
table_DF1: (2412, 11)
table_DF2: (303, 9)
table_DF3: (114, 10)
table_DF4: (100, 11)
table_DF5: (20, 11)
table_DF6: (1978, 11)
table_DF7: (99, 12)
table_DF8: (3, 12)
table_DF1: (2592, 11)
table_DF2: (304, 9)
table_DF3: (114, 10)
table_DF4: (104, 11)
table_DF5: (21, 11)
table_DF6: (2260, 11)
table_DF7: (118, 12)
table_DF8: (3, 12)
table_DF1: (2724, 11)
table_DF2: (304, 9)
table_DF3: (114, 10)
table_DF4: (106, 11)
table_DF5: (23, 11)
table_DF6: (2536, 11)
table_DF7: (140, 12)
table_DF8: (4, 12)
table_DF1: (2928, 11)
table_DF2: (305, 9)
table_DF3: (115, 10)
table_DF4: (109, 11)
table_DF5: (26, 11)
table_DF6: (2775, 11)
table_DF7: (152, 12)
table_DF8: (4, 12)
table_DF1: (3126, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (116, 11)
table_DF5: (26, 11)
table_DF6: (3038, 11)
table_DF7: (173, 12)
table_DF8: (4, 12)
table_DF1: (3272, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (120, 11)
table_DF5: (26, 11)
table_DF6: (3223, 11)
table_DF7: (186, 12)
table_DF8: (5, 12)
table_DF1: (3578, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3352, 11)
table_DF7: (197, 12)
table_DF8: (5, 12)
table_DF1: (4124, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3509, 11)
table_DF7: (213, 12)
table_DF8: (5, 12)
table_DF1: (4526, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3594, 11)
table_DF7: (219, 12)
table_DF8: (6, 12)
table_DF1: (4818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3678, 11)
table_DF7: (233, 12)
table_DF8: (6, 12)
table_DF1: (4932, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3780, 11)
table_DF7: (248, 12)
table_DF8: (6, 12)
table_DF1: (5078, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3852, 11)
table_DF7: (259, 12)
table_DF8: (6, 12)
table_DF1: (5172, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3906, 11)
table_DF7: (273, 12)
table_DF8: (6, 12)
table_DF1: (5274, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (3995, 11)
table_DF7: (284, 12)
table_DF8: (9, 12)
table_DF1: (5412, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4065, 11)
table_DF7: (294, 12)
table_DF8: (9, 12)
table_DF1: (5566, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4146, 11)
table_DF7: (304, 12)
table_DF8: (10, 12)
table_DF1: (5726, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4191, 11)
table_DF7: (312, 12)
table_DF8: (12, 12)
table_DF1: (5888, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4252, 11)
table_DF7: (319, 12)
table_DF8: (13, 12)
table_DF1: (6068, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4304, 11)
table_DF7: (326, 12)
table_DF8: (14, 12)
table_DF1: (6496, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4363, 11)
table_DF7: (334, 12)
table_DF8: (15, 12)
table_DF1: (6768, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4424, 11)
table_DF7: (341, 12)
table_DF8: (16, 12)
table_DF1: (7082, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4454, 11)
table_DF7: (347, 12)
table_DF8: (16, 12)
table_DF1: (7158, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4490, 11)
table_DF7: (354, 12)
table_DF8: (16, 12)
table_DF1: (7268, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4520, 11)
table_DF7: (361, 12)
table_DF8: (16, 12)
table_DF1: (7386, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4561, 11)
table_DF7: (366, 12)
table_DF8: (16, 12)
table_DF1: (7462, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4603, 11)
table_DF7: (370, 12)
table_DF8: (16, 12)
table_DF1: (7540, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4631, 11)
table_DF7: (373, 12)
table_DF8: (16, 12)
table_DF1: (7640, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4666, 11)
table_DF7: (378, 12)
table_DF8: (16, 12)
table_DF1: (7742, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4704, 11)
table_DF7: (381, 12)
table_DF8: (16, 12)
table_DF1: (7838, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4730, 11)
table_DF7: (385, 12)
table_DF8: (16, 12)
table_DF1: (7936, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4760, 11)
table_DF7: (389, 12)
table_DF8: (16, 12)
table_DF1: (8218, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4789, 11)
table_DF7: (391, 12)
table_DF8: (16, 12)
table_DF1: (8390, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4812, 11)
table_DF7: (394, 12)
table_DF8: (16, 12)
table_DF1: (8556, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4827, 11)
table_DF7: (396, 12)
table_DF8: (16, 12)
table_DF1: (8682, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4843, 11)
table_DF7: (399, 12)
table_DF8: (16, 12)
table_DF1: (8760, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4865, 11)
table_DF7: (403, 12)
table_DF8: (16, 12)
table_DF1: (8832, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4885, 11)
table_DF7: (406, 12)
table_DF8: (16, 12)
table_DF1: (8880, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4903, 11)
table_DF7: (409, 12)
table_DF8: (16, 12)
table_DF1: (8928, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4919, 11)
table_DF7: (411, 12)
table_DF8: (16, 12)
table_DF1: (8986, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4932, 11)
table_DF7: (412, 12)
table_DF8: (16, 12)
table_DF1: (9038, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4941, 11)
table_DF7: (414, 12)
table_DF8: (16, 12)
table_DF1: (9104, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4958, 11)
table_DF7: (414, 12)
table_DF8: (16, 12)
table_DF1: (9150, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4978, 11)
table_DF7: (417, 12)
table_DF8: (16, 12)
table_DF1: (9368, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)

table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (4989, 11)
table_DF7: (417, 12)
table_DF8: (16, 12)
table_DF1: (9532, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5004, 11)
table_DF7: (417, 12)
table_DF8: (16, 12)
table_DF1: (9704, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5016, 11)
table_DF7: (417, 12)
table_DF8: (16, 12)
table_DF1: (9820, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5034, 11)
table_DF7: (418, 12)
table_DF8: (16, 12)
table_DF1: (9884, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5041, 11)
table_DF7: (418, 12)
table_DF8: (16, 12)
table_DF1: (9938, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5047, 11)
table_DF7: (418, 12)
table_DF8: (16, 12)
table_DF1: (9976, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5057, 11)
table_DF7: (420, 12)
table_DF8: (16, 12)
table_DF1: (10020, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5062, 11)
table_DF7: (420, 12)
table_DF8: (16, 12)
table_DF1: (10060, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5071, 11)
table_DF7: (420, 12)
table_DF8: (16, 12)
table_DF1: (10086, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5077, 11)
table_DF7: (420, 12)
table_DF8: (16, 12)
table_DF1: (10142, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5084, 11)
table_DF7: (420, 12)
table_DF8: (16, 12)
table_DF1: (10172, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5093, 11)
table_DF7: (421, 12)
table_DF8: (16, 12)
table_DF1: (10272, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5100, 11)
table_DF7: (422, 12)
table_DF8: (16, 12)
table_DF1: (10362, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5106, 11)
table_DF7: (422, 12)
table_DF8: (16, 12)
table_DF1: (10488, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5110, 11)
table_DF7: (422, 12)
table_DF8: (16, 12)
table_DF1: (10554, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5114, 11)
table_DF7: (422, 12)
table_DF8: (16, 12)
table_DF1: (10582, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5123, 11)
table_DF7: (422, 12)
table_DF8: (16, 12)
table_DF1: (10606, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5132, 11)
table_DF7: (422, 12)
table_DF8: (16, 12)
table_DF1: (10624, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5140, 11)
table_DF7: (424, 12)
table_DF8: (16, 12)
table_DF1: (10654, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5146, 11)
table_DF7: (424, 12)
table_DF8: (16, 12)
table_DF1: (10688, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5153, 11)
table_DF7: (424, 12)
table_DF8: (16, 12)
table_DF1: (10714, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5158, 11)
table_DF7: (424, 12)
table_DF8: (16, 12)
table_DF1: (10750, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5163, 11)
table_DF7: (424, 12)
table_DF8: (16, 12)
table_DF1: (10776, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5173, 11)
table_DF7: (426, 12)
table_DF8: (16, 12)
table_DF1: (10830, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5179, 11)
table_DF7: (426, 12)
table_DF8: (16, 12)
table_DF1: (10920, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5184, 11)
table_DF7: (426, 12)
table_DF8: (16, 12)
table_DF1: (11008, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5187, 11)
table_DF7: (426, 12)
table_DF8: (16, 12)
table_DF1: (11072, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5190, 11)
table_DF7: (426, 12)
table_DF8: (16, 12)
table_DF1: (11108, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5195, 11)
table_DF7: (427, 12)
table_DF8: (16, 12)
table_DF1: (11124, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5195, 11)
table_DF7: (427, 12)
table_DF8: (16, 12)
table_DF1: (11142, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5196, 11)
table_DF7: (428, 12)
table_DF8: (16, 12)
table_DF1: (11164, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5202, 11)
table_DF7: (429, 12)
table_DF8: (16, 12)
table_DF1: (11186, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5208, 11)
table_DF7: (429, 12)
table_DF8: (16, 12)
table_DF1: (11214, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5210, 11)
table_DF7: (429, 12)
table_DF8: (16, 12)
table_DF1: (11224, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5216, 11)
table_DF7: (429, 12)
table_DF8: (16, 12)
table_DF1: (11236, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5219, 11)
table_DF7: (429, 12)
table_DF8: (16, 12)
table_DF1: (11258, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5225, 11)
table_DF7: (431, 12)
table_DF8: (16, 12)
table_DF1: (11312, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5230, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11346, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5237, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11380, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5241, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11390, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5247, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11396, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5255, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11408, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5261, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11414, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5262, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11424, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5265, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11442, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5268, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11454, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5273, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11462, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5274, 11)
table_DF7: (432, 12)
table_DF8: (16, 12)
table_DF1: (11468, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5275, 11)
table_DF7: (434, 12)
table_DF8: (16, 12)
table_DF1: (11522, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)

table_DF5: (26, 11)
table_DF6: (5282, 11)
table_DF7: (434, 12)
table_DF8: (16, 12)
table_DF1: (11550, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5287, 11)
table_DF7: (434, 12)
table_DF8: (16, 12)
table_DF1: (11590, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5289, 11)
table_DF7: (434, 12)
table_DF8: (16, 12)
table_DF1: (11604, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5290, 11)
table_DF7: (434, 12)
table_DF8: (16, 12)
table_DF1: (11616, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5292, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11618, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5299, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11618, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5300, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11632, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5302, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11644, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5305, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11650, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5306, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11660, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5308, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11670, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5309, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11696, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5312, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11720, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5313, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11730, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5313, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11736, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5315, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11746, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5315, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11752, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5316, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11760, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5317, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11772, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5318, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11780, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5319, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11784, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5320, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11786, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5321, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11792, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5321, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11798, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5322, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11798, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5323, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11806, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5324, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11814, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5325, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11816, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5326, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11816, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5327, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11816, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5328, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5328, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5329, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5330, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5331, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5331, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5332, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11818, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5333, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11824, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5333, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11826, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5333, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11826, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5333, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11826, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5333, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)
table_DF1: (11826, 11)
table_DF2: (306, 9)
table_DF3: (117, 10)
table_DF4: (121, 11)
table_DF5: (26, 11)
table_DF6: (5334, 11)
table_DF7: (435, 12)
table_DF8: (16, 12)

In [198]:
table_DF1.평가일.str.slice(0,4).value_counts()

2020    2838
2021    2328
2019    2222
2018    1450
2017    1108
2016     670
2015     524
2014     268
2013     210
2012     138
2011      60
2010      10
Name: 평가일, dtype: int64

In [205]:
table_DF1=table_DF1.drop_duplicates()
table_DF2=table_DF2.drop_duplicates()
table_DF3=table_DF3.drop_duplicates()
table_DF4=table_DF4.drop_duplicates()
table_DF5=table_DF5.drop_duplicates()
table_DF6=table_DF6.drop_duplicates()
table_DF7=table_DF7.drop_duplicates()
table_DF8=table_DF8.drop_duplicates()

In [209]:
print("table_DF1:",table_DF1.shape)
print("table_DF2:",table_DF2.shape)
print("table_DF3:",table_DF3.shape)
print("table_DF4:",table_DF4.shape)
print("table_DF5:",table_DF5.shape)
print("table_DF6:",table_DF6.shape)
print("table_DF7:",table_DF7.shape)
print("table_DF8:",table_DF8.shape)

table_DF1: (11620, 11)
table_DF2: (299, 9)
table_DF3: (114, 10)
table_DF4: (119, 11)
table_DF5: (25, 11)
table_DF6: (5216, 11)
table_DF7: (420, 12)
table_DF8: (16, 12)

In [212]:
os.chdir('C:\\Users\\kuri9\\Desktop\\Crawling\\Desktop\\Project\\1_Data')
table_DF1.to_csv('KOREA_CREDIT_1.csv',index=False)
table_DF2.to_csv('KOREA_CREDIT_2.csv',index=False)
table_DF3.to_csv('KOREA_CREDIT_3.csv',index=False)
table_DF4.to_csv('KOREA_CREDIT_4.csv',index=False)
table_DF5.to_csv('KOREA_CREDIT_5.csv',index=False)
table_DF6.to_csv('KOREA_CREDIT_6.csv',index=False)
table_DF7.to_csv('KOREA_CREDIT_7.csv',index=False)
table_DF8.to_csv('KOREA_CREDIT_8.csv',index=False)

In [213]:
os.getcwd()

'C:\\Users\\kuri9\\Desktop\\Crawling\\Desktop\\Project\\1_Data'